apiVersion: apps/v1
kind: Deployment
metadata:
  name: myfirstdosa
spec:
  selector:
    matchLabels:
      app: myfirstdosa
  replicas: 1 
  template: 
    metadata:
      labels:
        app: myfirstdosa
    spec:
      containers:
      - name: helloworld
        image: cpavan811/myfirstdosa:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
 name: myfirstdosa
spec:
 type: NodePort
 selector:
   app: myfirstdosa
 ports:
   - name: client
     protocol: TCP
     port: 80
     nodePort: 32080
 selector:
   app: myfirstdosa
